version: "3"

services:
  # Auth server
  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile.web
    image: ct-auth-server:latest
    env_file:
      - ./auth-server/.env
    environment:
      - PORT=5006
      - MONGODB_URI=mongodb://auth-db:27017/auth-db
    ports:
      - "5006:5006"
    depends_on:
      - auth-db
    networks:
      - access-network
      - auth-network
  
  # Ingress gateways
  user-api:
    build:
      context: ./user-api
      dockerfile: Dockerfile.web
    image: ct-user-api:latest
    environment:
      - PORT=5000
      - VISIT_MANAGER_URL=http://visit-manager:5005
      - AUTH_SERVER_URL=http://auth-server:5006
    ports:
      - "5000:5000"
    networks:
      - access-network
      - internal-network

  # Back-end servers
  visit-manager:
    build:
      context: ./visit-manager
      dockerfile: Dockerfile.web
    image: ct-visit-manager:latest
    command: "sleep 5 && npm start"
    environment:
      - PORT=5005
      - MONGODB_URI=mongodb://contact-tracing-db:27017/contact-tracing-db
    ports:
      - "5005:5005"
    depends_on:
      - contact-tracing-db
    networks:
      - internal-network

  # Back-end servers
  virus-tracker:
    build:
      context: ./virus-tracker
      dockerfile: Dockerfile.web
    image: ct-virus-tracker:latest
    command: "sleep 5 && npm start"
    environment:
      - PORT=5007
      - MONGODB_URI=mongodb://contact-tracing-db:27017/contact-tracing-db
    ports:
      - "5007:5007"
    depends_on:
      - contact-tracing-db
    networks:
      - internal-network
      - access-network

  # DBs
  contact-tracing-db:
    image: mongo:3.6.4
    volumes:
      - './data:/data/db'
    networks:
      - internal-network
  auth-db:
    image: mongo:3.6.4
    volumes:
      - './data-auth:/data/db'
    networks:
      - auth-network

networks:
  internal-network:
  access-network:
  auth-network: