version: "3"

services:
  # Ingress gateways
  user-api:
    build:
      context: ./user-api
      dockerfile: Dockerfile.web
    image: ct-user-api:latest
    environment:
      - PORT=5000
      - VISIT_MANAGER_URL=http://visit-manager:5005
      - VIRUS_TRACKER_URL=http://virus-tracker:5007
    ports:
      - "5000:5000"
    networks:
      - access-network
      - internal-network

  # Back-end servers
  visit-manager:
    build:
      context: ./visit-manager
      dockerfile: Dockerfile.web
    image: ct-visit-manager:latest
    command: "sleep 5 && npm start"
    environment:
      - PORT=5005
      - MONGODB_URI=mongodb://contact-tracing-db-fresh:27017/contact-tracing-db-fresh
    ports:
      - "5005:5005"
    depends_on:
      - contact-tracing-db-fresh
    networks:
      - internal-network

  virus-tracker:
    build:
      context: ./virus-tracker
      dockerfile: Dockerfile.web
    image: ct-virus-tracker:latest
    command: "sleep 5 && npm start"
    environment:
      - PORT=5007
      - MONGODB_URI=mongodb://contact-tracing-db-fresh:27017/contact-tracing-db-fresh
      - MONGODB_DB_NAME=contact-tracing-db-fresh
      - QUEUE_ADDRESS=amqp://guest:guest@codes-queue-fresh:5672/
      - QUEUE_NAME=infected-codes
    ports:
      - "5007:5007"
    depends_on:
      - contact-tracing-db-fresh
      - codes-queue-fresh
    networks:
      - internal-network
      - codes-queue-network

  contagion-updater:
    build:
      context: ./contagion-updater
      dockerfile: Dockerfile
    image: ct-contagion-updater:latest
    environment:
      - MONGODB_URI=mongodb://contact-tracing-db-fresh:27017/contact-tracing-db-fresh
      - QUEUE_ADDRESS=amqp://codes-queue/
      - QUEUE_NAME=infected-codes
    depends_on:
      - codes-queue-fresh
    networks:
      - internal-network
      - codes-queue-network

  # RabbitMQ instance
  codes-queue-fresh:
    image: rabbitmq:3-management-alpine
    ports:
        - 15672:15672
    networks:
        - codes-queue-network

  codes-whisperer:
    build:
      context: ./codes-whisperer
      dockerfile: Dockerfile.web
    image: ct-codes-whisperer:latest
    command: "sleep 5 && npm start"
    environment:
      - PORT=5008
      - MONGODB_URI=mongodb://contact-tracing-db:27017/contact-tracing-db
    ports:
      - "5008:5008"
    depends_on:
      - contact-tracing-db
    networks:
      - internal-network

  # DBs
  contact-tracing-db-fresh:
    image: mongo:3.6.4
    networks:
      - internal-network

networks:
  internal-network:
  access-network:
  codes-queue-network:
